Automatisch invullen standaardprofielen optioneel (#32)
* Stappen los

* Uitleg en naamgeving

* taludvoorkeur laag toegevoegd

* Add decimal to solve error in the description

Traceback (most recent call last):
  File "C:\Users\jacostabarragan\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\legger\views\calculating_profiles.py", line 168, in execute_step3_calculate_variants
    create_variants(self.polder_datasource)
  File "C:\Users\jacostabarragan\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\legger\utils\theoretical_profiles.py", line 450, in create_variants
    hydraulic_depth_list = get_depth_list(from_depth, to_depth)
  File "C:\Users\jacostabarragan\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\legger\utils\theoretical_profiles.py", line 132, in get_depth_list
    depth += 0.05
TypeError: unsupported operand type(s) for +=: 'decimal.Decimal' and 'float'

* add missing decimal

---------

Co-authored-by: jcacosta89 <78262040+jcacosta89@users.noreply.github.com>